services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "3004:3004"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge